name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    - name: setup
      run: mkdir build
    - name: debug
      run: pwd && cd build && pwd && ls -lah
    - name: cmake
      run: cd build && cmake ..
    - name: make
      run: cd build && make
    - name: Run sorting
      run: cd build && ./sorting
    - name: Run searching
      run: cd build && ./searching
    - name: Run graphs
      run: cd build && ./graphs

