name: algorithms

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: setup
      run: mkdir build
      run: cd build
    - name: run cmake
      run: cmake ..
    - name: make
      run: make
    - name: run sorting
      run: ./sorting
    - name: run searching
      run: ./searching
    - name: run graphs
      run: ./graphs

